name: HiFi_Net
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - ffmpeg=4.3
  - fftw=3.3.9
  - freetype=2.12.1
  - frozenlist=1.3.3
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - icu=67.1
  - idna=3.4
  - imageio=2.9.0
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - oauthlib=3.2.1
  - openh264=2.1.1
  - openssl=1.1.1w
  - pillow=9.4.0
  - pip=23.3.2
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7.16
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchvision=0.12.0
  - tornado=5.1.1
  - tqdm=4.64.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.14
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xz=5.4.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - einops==0.6.1
    - kmeans-pytorch==0.3
    - opencv-python==4.8.1.78
    - supervision==0.11.1

