name: c2p
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pip:
      - torch==2.3.1
      - torchvision==0.18.1
      - torchaudio==2.3.1
      - transformers==4.25.0
      - accelerate
      - scikit-image
      - opencv-python