name: propainter
channels:
  - conda-forge
  - defaults
dependencies:
  # Installer Python via Conda
  - python=3.8
  - pip
  - conda-forge::ffmpeg #delete this line if you already have ffmpeg on your machine
  # Installer tous les packages via pip
  - pip:
      - av
      - addict
      - einops
      - ffmpeg-python 
      - future
      - numpy
      - scipy
      - opencv-python
      - matplotlib
      - scikit-image
      - torch>=1.7.1
      - torchvision>=0.8.2
      - imageio-ffmpeg
      - pyyaml
      - requests
      - timm
      - yapf