compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  deepspeed_config_file: config/deepspeed_config.json
  deepspeed_multinode_launcher: standard
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 29503
main_training_function: main
num_machines: 1
num_processes: 8
# gpu_ids: 0
use_cpu: false
